"""Clean TGVF defaults."""

DEFAULT_MODEL_FAMILY = "Qwen3-VL-8B-Thinking"
DEFAULT_MODEL_ID = "Qwen/Qwen3-VL-8B-Thinking"
DEFAULT_PROTOCOL = "protocol_c_tool_observation"
DEFAULT_CONTINUATION = "natural_continue"
DEFAULT_BENCHMARK_ROOT = "/home/dredvpn009/Flash_Storage/datasets/benchmarks"
DEFAULT_MAX_IMAGE_RESOLUTION = 512
DEFAULT_STAGE1_GLOBAL_BATCH = 32
DEFAULT_STAGE2_GLOBAL_BATCH = 128
DEFAULT_STAGE1_MAX_STEPS = 2000
DEFAULT_STAGE2_MAX_STEPS = 1200
DEFAULT_PARSER_IDENTITY = "v3_external_parse_and_score"
DEFAULT_CHOICE_PARSER_IDENTITY = "extract_choice_strict"
DEFAULT_SCORING_BACKEND = "auto"
DEFAULT_CORE_DEV_SUBSET_ID = "core_balanced_dev_2511_seed20260625"
DEFAULT_CORE_DEV_SHORT_NAME = "CoreDev-2511"
